### ISSUE TITLE
dataset issue

### ISSUE THREAD

**Issue by AaronWhite95** [DFKI-NLP/TRE#3]
Excuse me, how can I get the TACRED dataset or how can I get the LDC publication?
Thank you.

**Comment by ChristophAlt** [comment]
The TACRED dataset is released by the Linguistic Data Consortium (LDC). You can download it from the [TACRED webpage](https://catalog.ldc.upenn.edu/LDC2018T24). If you are an LDC member, the access is free, otherwise a fee of 25$ applies.
