### ISSUE TITLE
ModuleNotFoundError: No module named '_regex'

### ISSUE THREAD

**Issue by vhientran** [DFKI-NLP/TRE#5]
I downloaded Trained Models to produce your paper results. However, for SemEval2010 Task 8, it is an error when evaluating:

File "/var/autofs/cl/work/TRE-master/train_utils.py", line 97, in load_model
    text_encoder = pickle.load(f)
ModuleNotFoundError: No module named '_regex'

The above error is appeared when I try to run this command below:

CUDA_VISIBLE_DEVICES=0 python relation_extraction.py evaluate --dataset semeval_2010_task8 --test-file datasets/semeval_jsonl/semeval_2010_task8/test.jsonl --log-dir  logs/ --save-dir logs/official_model/tre_semeval

Please help me to consider this problem. Thank you so much.

**Comment by marchbnr** [comment]
It seems like you are missing the regex module.

Either install regex like this:
`pip install regex==2017.4.5`
or install all of the required dependencies (in case you are lacking others as well):
`pip install -r requirements.txt`

**Comment by vhientran** [comment]
Thank you for the quick reply. I will try to fix this problem.
